[package]
name = "brie_daw"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
rodio = "0.19.0"

sdl2 = { version = "0.37.0", features = ["image", "ttf"] }
serde = { version = "1.0.210", features = ["serde_derive"] }
